In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Prueba de RandomForest sobre por qué está clasificando con un vector

In [48]:
x = np.random.randint(5, size=(100,10))
y = np.random.randint(2, size=(100))

In [49]:
s = int(len(x)*0.7)
x_train, y_train = x[:s], y[:s]
x_test, y_test = x[s:], y[s:]

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [52]:
rf.score(x_test, y_test)

0.40000000000000002

In [53]:
n = 99
rf.predict(x[n])

/usr/local/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [54]:
x[n], y[n]

(array([2, 3, 1, 3, 2, 3, 0, 2, 1, 3]), 1)

Dataframes concatenate

In [15]:
df = pd.DataFrame({
        "A": [1,2,3,4],
        "B": [2,3,4,5]
    })
df_new = pd.DataFrame({
        "result": [1,0,1,1]
    })

In [44]:
dfdfa ={
        "x": [1,2,3,4],
        "B": [2,3,4,5],
    "C": [21231]
    }

In [19]:
df.join(df_new)

A  B  result
0  1  2       1
1  2  3       0
2  3  4       1
3  4  5       1

In [27]:
df_ = pd.DataFrame()

In [25]:
df_.append(df.join(df_new))

In [30]:
for i in range(10):
    df_ = df_.append(df.join(df_new))

In [45]:
for i in list(dfdfa.keys()):
    print(i)

C
x
B


In [46]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
%time > resultado.txt
3

SyntaxError: invalid syntax (<unknown>, line 1)

In [62]:
Out[60]

3