In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Prueba de RandomForest sobre por qué está clasificando con un vector

In [48]:
x = np.random.randint(5, size=(100,10))
y = np.random.randint(2, size=(100))

In [49]:
s = int(len(x)*0.7)
x_train, y_train = x[:s], y[:s]
x_test, y_test = x[s:], y[s:]

In [50]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [52]:
rf.score(x_test, y_test)

0.40000000000000002

In [53]:
n = 99
rf.predict(x[n])

/usr/local/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([0])

In [54]:
x[n], y[n]

(array([2, 3, 1, 3, 2, 3, 0, 2, 1, 3]), 1)

Dataframes concatenate

In [15]:
df = pd.DataFrame({
        "A": [1,2,3,4],
        "B": [2,3,4,5]
    })
df_new = pd.DataFrame({
        "result": [1,0,1,1]
    })

In [44]:
dfdfa ={
        "x": [1,2,3,4],
        "B": [2,3,4,5],
    "C": [21231]
    }

In [19]:
df.join(df_new)

A  B  result
0  1  2       1
1  2  3       0
2  3  4       1
3  4  5       1

In [27]:
df_ = pd.DataFrame()

In [25]:
df_.append(df.join(df_new))

In [30]:
for i in range(10):
    df_ = df_.append(df.join(df_new))

In [45]:
for i in list(dfdfa.keys()):
    print(i)

C
x
B


In [46]:
array = np.arange(20)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [78]:
data = pd.DataFrame([
        [15900, 2, 3, 5, 1, 0, 1, 1],
        [15901, 2, 3, 5, 1, 0, 1, 1],
        [15902, 3, 4, 1, 0, 0, 0, 1],
        [15903, 2, 3, 2, 1, 0, 0, 0],
        [15905, 2, 3, 4, 1, 0, 1, 1],
        [15906, 1, 1, 1, 0, 0, 1, 0],
        [15907, 2, 5, 2, 1, 0, 1, 0],
        [15908, 2, 3, 5, 1, 0, 1, 1],
        [15909, 2, 4, 2, 1, 1, 0, 1],
        [15910, 2, 3, 5, 0, 0, 1, 1]
    ], columns=["cod", "feature1", "feature2", "feature3", "target1", "target2", "target3", "target4"])
data.shape

(10, 8)

In [79]:
data

cod  feature1  feature2  feature3  target1  target2  target3  target4
0  15900         2         3         5        1        0        1        1
1  15901         2         3         5        1        0        1        1
2  15902         3         4         1        0        0        0        1
3  15903         2         3         2        1        0        0        0
4  15905         2         3         4        1        0        1        1
5  15906         1         1         1        0        0        1        0
6  15907         2         5         2        1        0        1        0
7  15908         2         3         5        1        0        1        1
8  15909         2         4         2        1        1        0        1
9  15910         2         3         5        0        0        1        1

In [47]:
data.columns.tolist()[4:]

['target1', 'target2', 'target3', 'target4']

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [97]:
data_features = data.iloc[:, 1:4].as_matrix()
data_targets = data.iloc[:, 4:].as_matrix()

In [88]:
A = [1,2,3,4,5,6,7,8,9, 10]

In [93]:
A[:6]

[1, 2, 3, 4, 5, 6]

In [92]:
A[6:]

[7, 8, 9, 10]

In [98]:
x_train = data_features[:6]
y_train = data_targets[:6]
x_test = data_features[6:]
y_test = data_targets[6:]
x_train.shape, x_test.shape

((6, 3), (4, 3))

In [29]:
rf = RandomForestClassifier()

In [39]:
rf.fit(x_train, y_train[:, 0])

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [40]:
rf.score(x_test, y_test[:, 0])

0.5

In [44]:
rf.predict(x_test[1].reshape(1, -1))

array([1])

In [99]:
data['cod'].loc[6:]

6    15907
7    15908
8    15909
9    15910
Name: cod, dtype: int64

In [103]:
resultados = pd.DataFrame(columns=data.columns.tolist()[0:1] + data.columns.tolist()[4:])
resultados['cod']  = data['cod'].loc[6:]
resultados

cod target1 target2 target3 target4
6  15907     NaN     NaN     NaN     NaN
7  15908     NaN     NaN     NaN     NaN
8  15909     NaN     NaN     NaN     NaN
9  15910     NaN     NaN     NaN     NaN

In [122]:
for i, col in enumerate(data.columns.tolist()[4:]):
    rf.fit(x_train, y_train[:, i])
    preds = [rf.predict(x.reshape(1, -1))[0] for x in x_test]
    resultados[col] = preds
resultados.to_csv('resultados.csv', index=False)

In [120]:
data.iloc[6:, [0,4,5,6,7]]

cod  target1  target2  target3  target4
6  15907        1        0        1        0
7  15908        1        0        1        1
8  15909        1        1        0        1
9  15910        0        0        1        1